# Generated by Django 5.1.4 on 2024-12-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='list',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
